### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by LeoJoy39** [NetEase-GameAI/ProPose#10]
Hello, thanks for your great work. I'm having some issues with data preparation now.
You said you prepare the data following [HybrIK](https://github.com/Jeff-sjtu/HybrIK#fetch-data), however, [HybrIK](https://github.com/Jeff-sjtu/HybrIK#fetch-data) only uses **Human3.6M**, **MPI-INF-3DHP**, **3DPW** and **MSCOCO** datasets to train their model, while ProPose uses **Human3.6M**, **MPI-INF-3DHP**, **MSCOCO**, **3DPW**, **EFT**, **AGORA**, **COCO-Wholebody** for trainning. I don't know how to prepare the datasets EFT and AGORA (for example, we can only get **COCO2014-All-ver01.json** file from EFT official website, while you use **NEW_COCO2014-All-ver01.pkl** file in your code, how to convert the .json file to corresponding .pkl; and I don't know what resolution of the images you use in agora dataset as well), neither do I know the directory structure of the data, like in [HybrIK](https://github.com/Jeff-sjtu/HybrIK#fetch-data).
Looking forward to your answer.

**Comment by LeoJoy39** [comment]
Sorry I think I didn't expressed clearly.
What I really need is the data directory structure of EFT and AGORA datasets, and corresponding process scripts. From the codes you show above, we still don't know how to get the .pkl files **COCO2014-All-ver01.pkl** and **person_keypoints_train2017.json_annot_with_id.pkl**，for we don't have the access to them from the official websites.

**Comment by raypine** [comment]
**COCO2014-All-ver01.pkl** is the raw file of EFT dataset, see [here ](https://github.com/facebookresearch/eft).
**person_keypoints_train2017.json_annot_with_id.pkl** is a dumped coco data file from our mscoco.py ([this line](https://github.com/NetEase-GameAI/ProPose/blob/main/propose/datasets/mscoco.py#L191)) and adding 'annotId': obj['id'] to the dict.

**Comment by raypine** [comment]
I have uploaded the data file of EFT and AGORA [here](https://drive.google.com/drive/folders/1JOE18euXSyw7oCeC9f58DQycZtV6X_Is?usp=sharing).
