### ISSUE TITLE
Are results tested with the predicted camera?

### ISSUE THREAD

**Issue by WeiyiNTime** [NetEase-GameAI/ProPose#14]
We note that there is no camera or 2D joint loss in the paper. 
But we find 2D joint loss in the code. 
There is a question about the evaluation: are the MPJPE or PA-MPJPE tested without the opitmization of the 2D loss?

**Comment by raypine** [comment]
We estimate the camera in AGORA as code shows. For other datasets, we follow HybrIK ("In the testing phase, the absolute depth of the root joint is obtained from RootNet") and use the annotations provided by them.

**Comment by WeiyiNTime** [comment]
Thanks a lot
