### ISSUE TITLE
测试代码

### ISSUE THREAD

**Issue by zengyiwen123** [NetEase-GameAI/ProPose#15]
请问可以提供测试代码吗？demo跑出来的效果不怎么好呀

**Comment by raypine** [comment]
你指的是在公开数据集还是在in-the-wild images上的效果？
测试代码和HybrIK一样。有几点影响：1）和他们一样需要用到额外估计的translation。2）现在开放的模型是为了兼容截断严重的半身图片（像跑酷之类），所以用的是直接回归相机系下的metric尺度的坐标。由于3DPW等benchmark截断问题较少，用heatmap的方式做关键点分支会提升不少精度。3）训练集划分比例。
