### ISSUE TITLE
About the SMPL annotations of h36m dataset

### ISSUE THREAD

**Issue by XiaobenLi00** [NetEase-GameAI/ProPose#6]
I know h36m is not a open source dataset, but I can only get 3D labels, could you provide some information about how to get SMPL annotations of it?

**Comment by raypine** [comment]
If the MoSh data is not available, you can follow the data process of HybrIK ([this section](https://github.com/Jeff-sjtu/HybrIK#fetch-data)) and he gets the data from [Moon](https://github.com/mks0601/3DMPPE_POSENET_RELEASE).

**Comment by XiaobenLi00** [comment]
Thanks a lot for your reply.
But I still wonder how you get the GT SMPL parameters of h36m, did you apply Mosh to the marker data or you get them somewhere?

**Comment by XiaobenLi00** [comment]
> Thanks a lot for your reply. But I still wonder how you get the GT SMPL parameters of h36m, did you apply Mosh to the marker data or you get them somewhere?

So did you follow the data process of HybrIK and get the data from Moon?

**Comment by XiaobenLi00** [comment]
> If the MoSh data is not available, you can follow the data process of HybrIK ([this section](https://github.com/Jeff-sjtu/HybrIK#fetch-data)) and he gets the data from [Moon](https://github.com/mks0601/3DMPPE_POSENET_RELEASE).

I check the annoation data from Moon, but it did not contain SMPL parameters right?

**Comment by raypine** [comment]
Actually It has the parameters in annotations (Human36M_subjectX_smpl_param.json).

**Comment by raypine** [comment]
Or you can just download the parsed annotations from Hybrik with the [link](https://drive.google.com/drive/folders/1tLA_XeZ_32Qk86lR06WJhJJXDYrlBJ9r).

**Comment by XiaobenLi00** [comment]
> Or you can just download the parsed annotations from Hybrik with the [link](https://drive.google.com/drive/folders/1tLA_XeZ_32Qk86lR06WJhJJXDYrlBJ9r).

Yes, I can find annotations in this link.

**Comment by XiaobenLi00** [comment]
> Actually It has the parameters in annotations (Human36M_subjectX_smpl_param.json).

But sorry for this, I cannot find *smpl_param.json in the 'annotations'
<img width="731" alt="image" src="https://github.com/NetEase-GameAI/ProPose/assets/32378119/feb10515-1657-4b16-b467-72e75406e124">

**Comment by raypine** [comment]
Oh..., I guess Moon has modified this file. Nevertheless, the data from HybrIK is still complete, right ?

**Comment by XiaobenLi00** [comment]
> Oh..., I guess Moon has modified this file. Nevertheless, the data from HybrIK is still complete, right ?

These are the data from HybrIK
<img width="336" alt="image" src="https://github.com/NetEase-GameAI/ProPose/assets/32378119/752efbe7-811d-475c-961c-a7b190b3ab88">
And I find a data list in other repository of Moon[I2L-MeshNet](https://github.com/mks0601/I2L-MeshNet_RELEASE), the data link is [smpl](https://drive.google.com/drive/folders/12fCumEgs9PXT-dAaOGq0EDpl9dGKKorF) and the data is as follows
<img width="659" alt="image" src="https://github.com/NetEase-GameAI/ProPose/assets/32378119/5610577c-d001-48e5-acf3-9269da9fab57">
So are these data indeed the 'Human36M_subjectX_smpl_param.json' as you said before?
Thanks again for your patience :)

**Comment by raypine** [comment]
Yes, that's right. I2L-meshnet uses the SMPL and posenet only uses 3D keypoints.

**Comment by XiaobenLi00** [comment]
> Yes, that's right. I2L-meshnet uses the SMPL and posenet only uses 3D keypoints.

Thanks a lot!
