### ISSUE TITLE
About Fine-tune

### ISSUE THREAD

**Issue by Eagleton** [NetEase-GameAI/ProPose#8]
Great work! But I have a question about fine-tune. Is there any way to fine-tune the pretrained model to fit video with not real human, like game video or CG?

**Comment by raypine** [comment]
You could prepare the data annotations like [this](https://github.com/NetEase-GameAI/ProPose/tree/main/propose/datasets#dataset-notes). Mapping the keypoints if the definition is different from SMPL. As for SMPL shape parameters, you could fix the branch and estimate the global translation (maybe a post process is required).
