### ISSUE TITLE
About the rendering of mesh

### ISSUE THREAD

**Issue by XiaobenLi00** [NetEase-GameAI/ProPose#9]
Hi, thanks for your wonderful work.

I notice that in your paper, the rendered mesh in white background is shadowed, like this (from Figure 1 of your paper)
<img width="733" alt="image" src="https://github.com/NetEase-GameAI/ProPose/assets/32378119/a00fd04f-c642-4916-8f7e-d7843989ef71">

What I am wondering is that how the shadow is produced? I notice that you use opendr instead of pyrender to render the mesh, so is the shadow produced by the rendering process in your code? https://github.com/NetEase-GameAI/ProPose/blob/fb0167471a06cbdf7986596ccfdf805344a20218/propose/utils/render.py#L16 

Since I am not so familiar with the rendering, I'll appreciate it if you can help to make it clear.

Another issue is that is the mesh is rendered with the original image, how to render it without the shadow?

Thanks a lot!

**Comment by raypine** [comment]
Oh, the figure in the paper is rendered by Blender for better visualization.

**Comment by XiaobenLi00** [comment]
> Oh, the figure in the paper is rendered by Blender for better visualization.

Thanks for replying.
